# Generated by Django 2.2.13 on 2020-06-26 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mumbletemps", "0005_simplify_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="tempuser",
            name="temp_link",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="mumbletemps.TempLink",
            ),
        ),
        migrations.AlterField(
            model_name="templink",
            name="link_ref",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
